#RED A
ha[0]=LA
ra[0]=LA

#RED B
hb[0]=LB
rb[0]=LB

#RED C
hc[0]=LC
rc[0]=LC

#RED D
hd[0]=LD
rd[0]=LD

#RED EA_B
ra[1]=EA_B
rb[1]=EA_B

#RED EA_C
rc[1]=EA_C
ra[2]=EA_C

#RED EC_E
rc[2]=EC_E
re[0]=EC_E

#RED EC_D
rc[3]=EC_D
rd[1]=EC_D

#RED EB_D
rd[2]=EB_D
rb[3]=EB_D

#RED EB_E
rb[2]=EB_E
re[1]=EB_E