options
{
    directory "/var/cache/bind";

    listen-on { 11.11.0.1; };

    allow-query { any; };

    recursion yes;

    allow-recursion { any; };

    forwarders { 8.8.8.8; };

    forward only;

};

zone "ramos.izo"
{
    type master;
    
    file "/etc/bind/db.ramos.izo";

};